### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by diegomustafamarino** [mgfgt/contracter#1]
Is it possible to create code to rent a Pegaxy Game horse directly in the contract? Without having to go through captcha ? This even before it appears on the rental screen?

**Comment by mgfgt** [comment]
Thats the end goal of this project, but tbh its a wip and idk if I'll ever get around to implementing it properly.

**Comment by diegomustafamarino** [comment]
I understand, it's not ready yet... I have 10 usdt available for donation. Thanks
